version: '3.8'

services:
  # PXE Server with Foreman/Katello
  pxe_server:
    build:
      context: .
      dockerfile: pxe_server.Dockerfile
    container_name: pxe_server
    hostname: pxe-server
    ports:
      - "3000:3000"  # Foreman web interface
      - "67:67/udp"  # DHCP
      - "69:69/udp"  # TFTP
      - "53:53/udp"  # DNS
      - "22:22"      # SSH
    volumes:
      - pxe_data:/var/lib/tftpboot
      - foreman_data:/var/lib/foreman
      - foreman_reports:/var/lib/foreman-reports
      - postgres_data:/var/lib/pgsql
      - mongodb_data:/var/lib/mongodb
    environment:
      - FOREMAN_VERSION=3.0
      - PXE_NETWORK=192.168.1.0/24
      - PXE_GATEWAY=192.168.1.1
      - PXE_DNS=8.8.8.8,8.8.4.4
    networks:
      - pxe_network
    restart: unless-stopped
    privileged: true  # Required for PXE services

  # Main Program API Server
  main_program:
    build:
      context: .
      dockerfile: main_program.Dockerfile
    container_name: main_program
    hostname: main-program
    ports:
      - "5000:5000"  # API server
    volumes:
      - foreman_reports:/var/lib/foreman-reports:ro
      - main_program_logs:/var/log/main_program
    environment:
      - FLASK_ENV=development
      - REPORTS_DIR=/var/lib/foreman-reports
    networks:
      - pxe_network
    depends_on:
      - pxe_server
    restart: unless-stopped

  # Development PXE Client (for testing)
  pxe_client:
    build:
      context: .
      dockerfile: pxe_client.Dockerfile
    container_name: pxe_client
    hostname: test-client
    volumes:
      - pxe_client_reports:/reports
      - pxe_client_logs:/var/log/diagnostics
    networks:
      - pxe_network
    depends_on:
      - pxe_server
    restart: unless-stopped
    profiles:
      - dev  # Only start in development mode

  # Monitoring and Dashboard
  monitoring:
    image: grafana/grafana:latest
    container_name: monitoring
    hostname: monitoring
    ports:
      - "3001:3000"  # Grafana dashboard
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin123
    networks:
      - pxe_network
    restart: unless-stopped
    profiles:
      - monitoring

volumes:
  pxe_data:
    driver: local
  foreman_data:
    driver: local
  foreman_reports:
    driver: local
  postgres_data:
    driver: local
  mongodb_data:
    driver: local
  main_program_logs:
    driver: local
  pxe_client_reports:
    driver: local
  pxe_client_logs:
    driver: local
  grafana_data:
    driver: local

networks:
  pxe_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
